### ISSUE TITLE
使用过程的报错

### ISSUE THREAD

**Issue by Dyson-c** [FISCO-BCOS/python-sdk#181]
在使用过程会出现如下错误，可以怎么解决

non-resource variables are not supported in the long term
INFO >> compile with nodejs compiler
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- /home/dyson/Dyson/FISCO_BFLC/python-sdk/solcjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/dyson/Dyson/FISCO_BFLC/python-sdk/solcjs:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/dyson/Dyson/FISCO_BFLC/python-sdk/solcjs' ]
}
Traceback (most recent call last):
  File "/home/dyson/Dyson/FISCO_BFLC/python-sdk/client/common/compiler.py", line 102, in compile_file
    Compiler.compile_with_js(sol_file, contract_name, output_path)
  File "/home/dyson/Dyson/FISCO_BFLC/python-sdk/client/common/compiler.py", line 49, in compile_with_js
    common.execute_cmd(command)
  File "/home/dyson/Dyson/FISCO_BFLC/python-sdk/client/common/common.py", line 113, in execute_cmd
    data = subprocess.check_output(cmd.split(), shell=False, universal_newlines=True)
  File "/home/dyson/anaconda3/envs/tf/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/dyson/anaconda3/envs/tf/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./solcjs', '--bin', '--abi', 'contracts/CommitteePrecompiled.sol', '-o', 'contracts']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 73, in <module>
    Compiler.compile_file("contracts/CommitteePrecompiled.sol")
  File "/home/dyson/Dyson/FISCO_BFLC/python-sdk/client/common/compiler.py", line 112, in compile_file
    raise CompileError("compile error for compile failed, error information: {}".format(e))
client.bcoserror.CompileError: compile error for compile failed, error information: Command '['./solcjs', '--bin', '--abi', 'contracts/CommitteePrecompiled.sol', '-o', 'contracts']' returned non-zero exit status 1.

**Comment by coderkentzhang** [comment]
检查solc编译器配置，如果solc编译器可执行文件未找到，按顺序会去找solcjs，solcjs依赖的nodejs环境同样默认未安装，就会报错

**Comment by Dyson-c** [comment]
nodejs已经有安装了。但还是会这样报错。
![image](https://user-images.githubusercontent.com/68522810/194758206-b8196e90-c3ce-4fd0-8ae4-55e84efa6373.png)

**Comment by Dyson-c** [comment]
solc编译情况如下
![image](https://user-images.githubusercontent.com/68522810/194759007-05b386f7-eff1-4726-8bc4-94ed95268bcb.png)

**Comment by coderkentzhang** [comment]
建议下载linux下的solc二进制文件，并精确配置，只要能编译就不会报相关的错。参考readme和client_config.py。
nodejs类型的编译器我没怎么用。nodejs版本迭代差异性比较大，如果你很熟悉它，可以试试，不然就还是用二进制的编译器吧。

**Comment by Dyson-c** [comment]
好的，修改完client_config.py。该报错解决了。感谢

**Comment by augetyMax** [comment]
> 好的，修改完client_config.py。该报错解决了。感谢

请问是怎么修改的，我也有相同的错误
改了一天了。。。没找到
